### PR TITLE
fix README file

### PR DESCRIPTION
**Pull request by olexii4**
Fix README file.  Change extension and variable names. 

Signed-off-by: Oleksii Orel <oorel@redhat.com>

### CODE REVIEW

**Comment by sunix** [comment]
OK Normally THEIA_EXTENSIONS is to be used in the future right ?

**Comment by benoitf** [comment]
future is THEIA_EXTENSIONS yes, we're about to change it on master to avoid confusion between extensions and plugins

**Comment by olexii4** [comment]
just to have a working variant for now. I spent the time to understand it

**Comment by olexii4** [comment]
What about extension name?
https://github.com/eclipse/che-theia-factory-extension/blob/master/che-theia-factory/package.json#L2
In README.md
che-theia-factory -> @eclipse/che-theia-factory

**Comment by olexii4** [comment]
WDYT?

**Comment by sunix** [comment]
The "extension name"  is actually the folder name... at least it is how it is implemented

**Comment by olexii4** [comment]
ok

**Comment by mmorhun** [comment]
No, extension name is the name in main package.json

**Pull request closed without merging**
